"""followers

Revision ID: 884f17c7df3a
Revises: 6ab3e3fb485a
Create Date: 2023-02-22 22:26:30.065203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884f17c7df3a'
down_revision = '6ab3e3fb485a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
